"""
MODULE: signal_tracker.py

Tracks every alert generated by the bot for 15 days.
Monitors price every scan and records outcomes.
Generates daily summary files.
Stores everything in JSON.

DATA STORED PER SIGNAL:
  - Full snapshot of all 60+ data fields at alert time
  - All 28 signal states at alert time
  - Score and reasons
  - Entry price
  - Price checks every scan for 15 days
  - Final outcome: max pump %, max dump %, result
  - Daily notifications if significant moves happen

FILES:
  data/signal_tracker/
    active.json          — signals currently being monitored
    completed.json       — signals that completed 15-day monitoring
    daily/YYYY-MM-DD.json — all signals that completed on this day
    lifetime/batch_001.json, batch_002.json ... — all signals in chunks of 100

TELEGRAM COMMANDS:
  /signals_active    — show all currently monitored signals
  /signals_history   — show last 20 completed signals
  /signals_stats     — accuracy stats
  /give_file         — sends JSON files of all lifetime signals (100 per file)
"""

import os
import json
import time
from datetime import datetime, timezone, timedelta
from typing import Optional
from modules.logger import get_logger
import config

log = get_logger("signal_tracker")

BASE_DIR     = "data_ls/signal_tracker"
ACTIVE_PATH  = f"{BASE_DIR}/active.json"
COMPLETED_PATH = f"{BASE_DIR}/completed.json"
DAILY_DIR    = f"{BASE_DIR}/daily"
LIFETIME_DIR = f"{BASE_DIR}/lifetime"
MONITOR_DAYS = 15


def _ensure_dirs():
    for d in [BASE_DIR, DAILY_DIR, LIFETIME_DIR]:
        os.makedirs(d, exist_ok=True)


def _load_json(path: str, default):
    try:
        if os.path.exists(path):
            with open(path) as f:
                return json.load(f)
    except Exception as e:
        log.warning(f"Failed to load {path}: {e}")
    return default


def _save_json(path: str, data) -> None:
    try:
        _ensure_dirs()
        with open(path, "w") as f:
            json.dump(data, f, indent=2, default=str)
    except Exception as e:
        log.error(f"Failed to save {path}: {e}")


# ══════════════════════════════════════════════════════════════════════
#  RECORD NEW SIGNAL
# ══════════════════════════════════════════════════════════════════════

def record_signal(symbol: str, data: dict, score_result: dict) -> str:
    """
    Record a new alert signal for 15-day monitoring.
    Saves COMPLETE snapshot of all 60+ data fields at alert time.
    Returns signal_id.
    """
    _ensure_dirs()

    signal_id = f"{symbol}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}"
    now_str   = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    price     = data.get("price") or 0

    # Fields to exclude from snapshot (internal/redundant/too large)
    EXCLUDE_FIELDS = {
        "signals", "reasons", "penalties",  # stored separately
        "price_checks", "notifications_sent",  # tracker fields
        "ob_exchange_depth", "oi_exchanges",
        "funding_per_exchange", "ls_per_exchange",  # large dicts
    }

    # Save COMPLETE snapshot — every field the scanner collected
    full_snapshot = {}
    for k, v in data.items():
        if k in EXCLUDE_FIELDS:
            continue
        # Serialize safely
        if isinstance(v, (str, int, float, bool, type(None))):
            full_snapshot[k] = v
        elif isinstance(v, (list, dict)):
            try:
                json.dumps(v)  # test if serializable
                full_snapshot[k] = v
            except Exception:
                full_snapshot[k] = str(v)[:200]
        else:
            try:
                full_snapshot[k] = float(v)
            except Exception:
                full_snapshot[k] = str(v)[:200]

    signal = {
        # ── Identity ──────────────────────────────────────────────
        "signal_id":    signal_id,
        "symbol":       symbol,
        "alert_time":   now_str,
        "alert_ts":     time.time(),
        "entry_price":  price,

        # ── Scoring ───────────────────────────────────────────────
        "score":        score_result.get("score"),
        "max_score":    score_result.get("max_score"),
        "strength":     score_result.get("strength"),
        "pct_score":    score_result.get("pct_score"),
        "has_momentum": score_result.get("has_momentum", False),
        "momentum_score": score_result.get("momentum_score", 0),

        # ── All triggered signals with point values ───────────────
        "signals_state": {
            k: {"triggered": bool(v[0]), "points": v[1]}
            if isinstance(v, (list, tuple)) and len(v) >= 2
            else {"triggered": bool(v), "points": 0}
            for k, v in score_result.get("signals", {}).items()
        },

        # ── Human-readable reasons list ───────────────────────────
        "reasons":   score_result.get("reasons", []),
        "penalties": score_result.get("penalties", []),

        # ── COMPLETE data snapshot (all 60+ fields) ───────────────
        "snapshot": full_snapshot,

        # ── Exchange aggregation sources ──────────────────────────
        "data_sources": {
            "oi_source":       data.get("oi_source"),
            "funding_source":  data.get("funding_source"),
            "ls_source":       data.get("ls_source"),
            "liq_source":      data.get("liq_source"),
            "ob_source":       data.get("ob_source"),
            "ob_exchanges":    data.get("ob_exchanges", []),
        },

        # ── 15-day tracking fields (updated each scan) ────────────
        "price_checks":       [],
        "max_pump_pct":       0.0,
        "max_dump_pct":       0.0,
        "peak_price":         price,
        "trough_price":       price,
        "peak_time":          now_str,
        "trough_time":        now_str,
        "notifications_sent": [],
        "status":             "active",
        "completed_time":     None,
        "final_result":       None,
        "expire_ts":          time.time() + MONITOR_DAYS * 86400,
    }

    # Add to active.json
    active = _load_json(ACTIVE_PATH, {})
    active[signal_id] = signal
    _save_json(ACTIVE_PATH, active)

    log.info(f"Signal recorded: {signal_id} entry=${price} score={signal['score']}")
    return signal_id


# ══════════════════════════════════════════════════════════════════════
#  UPDATE PRICES (called every scan)
# ══════════════════════════════════════════════════════════════════════

def _fetch_live_snapshot(symbol: str) -> dict:
    """
    Fetch a complete 60-field data snapshot for one coin on demand.
    Called when a TP milestone is hit but the coin wasn't in the current scan batch.
    Uses the same fetchers as the main scanner.
    Takes ~2-3 seconds per coin.
    """
    try:
        from modules import (
            binance_fetcher    as bf,
            aggregated_fetcher as af,
            technical_analysis as ta,
            sentiment_fetcher  as sf,
            news_fetcher       as nf,
            btc_market,
            scorer,
        )
        from concurrent.futures import ThreadPoolExecutor

        # Ticker data
        tickers = bf.get_24h_tickers()
        ticker  = tickers.get(symbol, {})
        if not ticker:
            return {}

        data = dict(ticker)

        # Market cap from batch cache (usually already fetched)
        mc_data = sf.get_market_data(symbol)
        data.update(mc_data or {})

        # OHLCV + all futures in parallel
        with ThreadPoolExecutor(max_workers=8) as ex:
            f_daily = ex.submit(bf.get_klines, symbol, "1d", 60)
            f_1h    = ex.submit(bf.get_klines, symbol, "1h", 72)
            f_oi    = ex.submit(af.get_aggregated_oi, symbol)
            f_fund  = ex.submit(af.get_aggregated_funding, symbol)
            f_ls    = ex.submit(af.get_aggregated_ls_ratio, symbol)
            f_liq   = ex.submit(af.get_aggregated_liquidations, symbol)
            f_ob    = ex.submit(af.get_aggregated_order_book, symbol)
            f_basis = ex.submit(bf.get_basis, symbol, ticker.get("price", 0))

            df_daily = f_daily.result()
            df_1h    = f_1h.result()
            data.update(f_oi.result()    or {})
            data.update(f_fund.result()  or {})
            data.update(f_ls.result()    or {})
            data.update(f_liq.result()   or {})
            data.update(f_ob.result()    or {})
            data.update(f_basis.result() or {})

        # Technical analysis
        if df_daily is not None and not df_daily.empty:
            data.update(ta.run_all_ta(
                df_daily, df_1h,
                oi_usd=data.get("oi_usd"),
                market_cap_usd=data.get("market_cap_usd")
            ))

        # BTC context + Fear & Greed (cached, instant)
        data.update(btc_market.get_btc_context())
        data.update(sf.get_fear_greed())

        # Community data from batch cache
        data.update(sf.get_coingecko_community(symbol))

        return data

    except Exception as e:
        log.warning(f"_fetch_live_snapshot failed for {symbol}: {e}")
        return {}


def update_prices(current_prices: dict,
                  current_highs: dict = None,
                  current_scan_data: dict = None) -> list:
    """
    Update all active signals with current prices.
    Returns list of notification dicts for signals that hit thresholds.

    current_prices:    {symbol: close_price}
    current_highs:     {symbol: candle_high} — catches intra-scan spikes
    current_scan_data: {symbol: full_data_dict} — full 60-field snapshot
                       saved at every TP milestone for complete analysis

    WHAT GETS SAVED AT EACH TP MILESTONE:
      - Full 60+ field snapshot (OI, funding, CVD, RSI, patterns etc.)
      - Price at milestone
      - % from entry
      - Days elapsed
      - Which threshold was hit
    """
    active = _load_json(ACTIVE_PATH, {})
    if not active:
        return []

    if current_highs is None:
        current_highs = {}
    if current_scan_data is None:
        current_scan_data = {}

    notifications = []
    now_ts  = time.time()
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    to_complete = []

    # Fields to exclude from TP snapshots (same as entry snapshot)
    EXCLUDE_FIELDS = {
        "signals", "reasons", "penalties",
        "price_checks", "notifications_sent",
        "ob_exchange_depth", "oi_exchanges",
        "funding_per_exchange", "ls_per_exchange",
    }

    for signal_id, sig in active.items():
        symbol      = sig["symbol"]
        entry_price = sig.get("entry_price") or 0
        if not entry_price:
            continue

        cur_price   = current_prices.get(symbol)
        candle_high = current_highs.get(symbol)

        if not cur_price:
            continue

        # NEVER use candle high (high_24h) for peak tracking.
        # high_24h covers the last 24 hours which includes price history
        # BEFORE our entry. A coin that pumped before we alerted will have
        # a high_24h far above our entry, causing false TP milestones.
        #
        # Only use cur_price (actual price at scan time).
        # This means we might miss a spike that happened between scans,
        # but that's acceptable — correctness > completeness.
        effective_high = cur_price
        pct_change     = (cur_price - entry_price) / entry_price * 100
        days_elapsed   = (now_ts - sig["alert_ts"]) / 86400

        # Regular price check (lightweight — every 15 min)
        check = {
            "ts":           now_str,
            "price":        cur_price,
            "high":         round(effective_high, 8),
            "pct_change":   round(pct_change, 2),
            "days_elapsed": round(days_elapsed, 1),
        }
        sig["price_checks"].append(check)

        # Update peak/trough
        if effective_high > sig["peak_price"]:
            sig["peak_price"] = effective_high
            sig["peak_time"]  = now_str
        if cur_price < sig["trough_price"]:
            sig["trough_price"] = cur_price
            sig["trough_time"]  = now_str

        sig["max_pump_pct"] = round(
            (sig["peak_price"] - entry_price) / entry_price * 100, 2
        )
        sig["max_dump_pct"] = round(
            (sig["trough_price"] - entry_price) / entry_price * 100, 2
        )

        peak_pct = sig["max_pump_pct"]
        dump_pct = sig["max_dump_pct"]

        pump_thresholds = getattr(config, "PUMP_NOTIFY_THRESHOLDS", [10, 20, 30, 50, 75, 100])
        dump_thresholds = getattr(config, "DUMP_NOTIFY_THRESHOLDS", [-10, -20, -30])

        # ── Build full TP snapshot ────────────────────────────────
        def _build_tp_snapshot(sym: str, threshold: int, pct: float) -> dict:
            """
            Full 60-field snapshot at this TP level.
            If coin was in current scan batch → use that data (free).
            If coin was NOT in scan batch → fetch live data now (one-time cost).
            This guarantees complete 60-field snapshots at every TP milestone.
            """
            snap = {
                "tp_threshold":   threshold,
                "pct_from_entry": round(pct, 2),
                "price_at_tp":    cur_price,
                "peak_at_tp":     sig["peak_price"],
                "days_elapsed":   round(days_elapsed, 2),
                "ts":             now_str,
            }

            # Try scan data first (already fetched, zero extra cost)
            full = current_scan_data.get(sym, {})

            # If coin was NOT in this scan → fetch live data now
            if not full or len(full) < 20:
                try:
                    log.info(f"TP snapshot: fetching live data for {sym} (not in scan batch)")
                    full = _fetch_live_snapshot(sym)
                except Exception as e:
                    log.warning(f"TP live fetch failed for {sym}: {e}")
                    full = {}

            # Merge into snapshot
            for k, v in full.items():
                if k in EXCLUDE_FIELDS:
                    continue
                if isinstance(v, (str, int, float, bool, type(None))):
                    snap[k] = v
                elif isinstance(v, (list, dict)):
                    try:
                        json.dumps(v)
                        snap[k] = v
                    except Exception:
                        snap[k] = str(v)[:200]

            snap["data_source"] = "scan_batch" if current_scan_data.get(sym) else "live_fetch"
            return snap

        # Ensure tp_snapshots dict exists
        if "tp_snapshots" not in sig:
            sig["tp_snapshots"] = {}

        # Check pump thresholds
        for threshold in pump_thresholds:
            notif_key = f"threshold_{threshold}"
            if notif_key not in sig["notifications_sent"] and peak_pct >= threshold:

                # Save full 60-field snapshot at this TP
                tp_key = f"pump_{threshold}"
                sig["tp_snapshots"][tp_key] = _build_tp_snapshot(
                    symbol, threshold, peak_pct
                )

                notifications.append({
                    "type":        "pump",
                    "signal_id":   signal_id,
                    "symbol":      symbol,
                    "threshold":   threshold,
                    "pct_change":  round(peak_pct, 2),
                    "current_pct": round(pct_change, 2),
                    "days":        round(days_elapsed, 1),
                    "entry":       entry_price,
                    "current":     cur_price,
                    "peak":        sig["peak_price"],
                    "score":       sig["score"],
                })
                sig["notifications_sent"].append(notif_key)

        # Check dump thresholds
        for threshold in dump_thresholds:
            notif_key = f"threshold_{threshold}"
            if notif_key not in sig["notifications_sent"] and dump_pct <= threshold:

                # Save full snapshot at this dump level too
                tp_key = f"dump_{abs(threshold)}"
                sig["tp_snapshots"][tp_key] = _build_tp_snapshot(
                    symbol, threshold, dump_pct
                )

                notifications.append({
                    "type":        "dump",
                    "signal_id":   signal_id,
                    "symbol":      symbol,
                    "threshold":   threshold,
                    "pct_change":  round(dump_pct, 2),
                    "current_pct": round(pct_change, 2),
                    "days":        round(days_elapsed, 1),
                    "entry":       entry_price,
                    "current":     cur_price,
                    "score":       sig["score"],
                })
                sig["notifications_sent"].append(notif_key)

        # Check if 15 days elapsed → complete
        if now_ts >= sig["expire_ts"]:
            to_complete.append(signal_id)

    # Complete expired signals
    completed = _load_json(COMPLETED_PATH, {})
    for signal_id in to_complete:
        sig = active.pop(signal_id)
        sig["status"]         = "completed"
        sig["completed_time"] = now_str
        max_pump = sig["max_pump_pct"]
        max_dump = sig["max_dump_pct"]
        if max_pump >= 20:
            sig["final_result"] = "pumped"
        elif max_dump <= -20:
            sig["final_result"] = "dumped"
        else:
            sig["final_result"] = "flat"
        completed[signal_id] = sig

        # Also save to daily file
        date_str   = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        daily_path = f"{DAILY_DIR}/{date_str}.json"
        daily      = _load_json(daily_path, {})
        daily[signal_id] = sig
        _save_json(daily_path, daily)

        # Add to lifetime batches
        _append_to_lifetime(sig)

        log.info(
            f"Signal completed: {signal_id} "
            f"pump={max_pump}% dump={max_dump}% result={sig['final_result']}"
        )

    _save_json(ACTIVE_PATH, active)
    _save_json(COMPLETED_PATH, completed)

    return notifications


def _append_to_lifetime(signal: dict) -> None:
    """Append to lifetime batch files (100 signals per file)."""
    _ensure_dirs()
    # Find the latest batch file
    batch_num  = 1
    while True:
        path = f"{LIFETIME_DIR}/batch_{batch_num:03d}.json"
        data = _load_json(path, [])
        if len(data) < 100:
            data.append(signal)
            _save_json(path, data)
            return
        batch_num += 1


# ══════════════════════════════════════════════════════════════════════
#  STATS
# ══════════════════════════════════════════════════════════════════════

def get_stats() -> dict:
    """Calculate accuracy stats from completed signals."""
    completed = _load_json(COMPLETED_PATH, {})
    active    = _load_json(ACTIVE_PATH, {})

    if not completed:
        return {
            "total_completed": 0,
            "active":          len(active),
            "pumped":          0,
            "dumped":          0,
            "flat":            0,
            "win_rate":        0,
            "avg_pump":        0,
            "best_pump":       0,
            "worst_dump":      0,
        }

    signals   = list(completed.values())
    pumped    = [s for s in signals if s.get("final_result") == "pumped"]
    dumped    = [s for s in signals if s.get("final_result") == "dumped"]
    flat      = [s for s in signals if s.get("final_result") == "flat"]
    avg_pump  = sum(s["max_pump_pct"] for s in pumped) / len(pumped) if pumped else 0
    best_pump = max((s["max_pump_pct"] for s in signals), default=0)
    worst     = min((s["max_dump_pct"] for s in signals), default=0)

    # Per-score-range breakdown
    score_buckets = {}
    for s in signals:
        score = s.get("score", 0)
        bucket = f"{(score // 3) * 3}-{(score // 3) * 3 + 2}"
        if bucket not in score_buckets:
            score_buckets[bucket] = {"total": 0, "pumped": 0}
        score_buckets[bucket]["total"] += 1
        if s.get("final_result") == "pumped":
            score_buckets[bucket]["pumped"] += 1

    return {
        "total_completed": len(signals),
        "active":          len(active),
        "pumped":          len(pumped),
        "dumped":          len(dumped),
        "flat":            len(flat),
        "win_rate":        round(len(pumped) / len(signals) * 100, 1),
        "avg_pump":        round(avg_pump, 1),
        "best_pump":       round(best_pump, 1),
        "worst_dump":      round(worst, 1),
        "score_buckets":   score_buckets,
    }


def get_active_signals() -> list:
    active = _load_json(ACTIVE_PATH, {})
    return sorted(active.values(), key=lambda x: x.get("alert_ts", 0), reverse=True)


def get_completed_signals(limit: int = 20) -> list:
    completed = _load_json(COMPLETED_PATH, {})
    signals   = sorted(completed.values(),
                       key=lambda x: x.get("completed_time", ""), reverse=True)
    return signals[:limit]


def get_lifetime_batch_paths() -> list:
    """Return all lifetime batch file paths."""
    _ensure_dirs()
    paths = []
    batch_num = 1
    while True:
        path = f"{LIFETIME_DIR}/batch_{batch_num:03d}.json"
        if os.path.exists(path):
            paths.append(path)
            batch_num += 1
        else:
            break
    return paths


def get_daily_file_path(date_str: str = None) -> Optional[str]:
    """Get path to daily summary file. Default = today."""
    if not date_str:
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    path = f"{DAILY_DIR}/{date_str}.json"
    return path if os.path.exists(path) else None
